### ISSUE TITLE
Composer error on install

### ISSUE THREAD

**Issue by PubliAlex** [blakej115/magic-forms#1]
Hello,

When I try to install your module, I get the following composer error : 

![image](https://user-images.githubusercontent.com/55833027/194029918-51a86457-7ef7-49bd-b357-20ba7216b795.png)

Installing it on octobercms 3.1. I associated your module to a project, then launch php artisan project:sync

Best regards,

Alex

**Comment by blakej115** [comment]
Please try again and let me know if the issue persists.

I was able to replicate and it appears I was able to fix by having October CMS repull the plugin.

Thanks!
