### ISSUE TITLE
No hint path defined OctoberCMS 3.2.12

### ISSUE THREAD

**Issue by az-vm** [blakej115/magic-forms#15]
OctoberCMS 3.2.12
Magic Forms version: 1.6.4

Hello

Im using the blakej115/magic-forms and since the last update of october i'm getting this error on "translate messages" ->

 "No hint path defined for [martin.forms]." on line 112 of /Applications/MAMP/htdocs/site/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php

Thank you,

**Comment by blakej115** [comment]
@az-vm I assume you are referring to using Magic Forms with the Translate plugin. Please update October CMS, Magic Forms, and Translate to their latest versions. Create another issue if the issue persists after that.

Thanks!

**Comment by az-vm** [comment]
@blakej115 yes it is, and i will update all and test it, so i will give you a feedback!

**Comment by az-vm** [comment]
@blakej115 i have a private question to, how i can do it to you ?

**Comment by blakej115** [comment]
@az-vm You can add me on Discord: blakej115

**Comment by az-vm** [comment]
@blakej115 ok! i will
