### ISSUE TITLE
submit form translate problem with setContext() method in Message-model

### ISSUE THREAD

**Issue by jannikholsten** [blakej115/magic-forms#16]
Hi,
I have an issue with the compatibility to the RainLab translate plugin.

I got this error after I submitted the form:
`BadMethodCallException: Call to undefined method RainLab\Translate\Models\Message::setContext()`

So obviously the setContext() method doesnt exists anymore since I moved to October 3.0. 

Please check it and fix it. 
Thanks.

**Comment by blakej115** [comment]
Pull request #18 has been merged in. I apologize for the delay.

Thanks!
