### ISSUE TITLE
Unable to send email notifications - "Email "0" does not comply with addr-spec of RFC 2822." on line 54

### ISSUE THREAD

**Issue by Tciferblatt** [blakej115/magic-forms#17]
OctoberCMS version: 3.2.19
Magic Forms version: 1.6.4

When activating e-mail notifications the form will throw the following error:

"Email "0" does not comply with addr-spec of RFC 2822." on line 54 of /home/tajumasazas/domains/[domain]/public_html/vendor/symfony/mime/Address.php

How can this be fixed? Thank you in advance!

**Comment by blakej115** [comment]
@ssi-com-pl is correct that this should resolve your issue. If not, feel free to open a new issue.

Thanks!
