### ISSUE TITLE
Issue in exports records..

### ISSUE THREAD

**Issue by Anjaan2077** [blakej115/magic-forms#7]
Hi,
when we have messages in records exports the records.
but we have no messages in records fields and click the exports button following errors occurred...
![Capture](https://user-images.githubusercontent.com/64153858/197098847-f5bf079d-bc3f-4b7d-8bd4-aa7077fb95d8.PNG)

Please solve this problem.

**Comment by blakej115** [comment]
This is fixed in [v1.6.4](https://github.com/blakej115/magic-forms/releases/tag/v1.6.4).

Thanks for the report!
