### ISSUE TITLE
Unable to send email notifications when sending a form

### ISSUE THREAD

**Issue by johrclaessens** [blakej115/magic-forms#9]
OctoberCMS version: 2.2.34
Magic Forms version: 1.6.4

When activating e-mail notifications in the component (both notifications and auto-response), the form will throw the following error:

`"Declaration of Egulias\EmailValidator\Validation\MessageIDValidation::isValid(string $email, Egulias\EmailValidator\EmailLexer $emailLexer): bool must be compatible with Egulias\EmailValidator\Validation\EmailValidation::isValid($email, Egulias\EmailValidator\EmailLexer $emailLexer)" on line 23 of **/home/**user**/domains/**domain.com**/public_html/vendor/egulias/email-validator/src/Validation/MessageIDValidation.php`**

**Comment by blakej115** [comment]
The latest compatible version of Magic Forms that is compatible with October CMS v2 is v1.5.2 of Magic Forms.

You should downgrade Magic Forms to 1.5.2 or update October CMS to v3.

Thanks!
